### ISSUE TITLE
Characters limitation does not match before submission and after submission.

### ISSUE THREAD

**Issue by j8xixo12** [chestercheng/pretalx#1]
### Problem and impact

 CFP page shows different characters limitation before submission and after submission.

### Expected behaviour

Characters limitation should be the same before and after submission.

### Steps to reproduce

1. Go to CFP proposal submission page.
2. Submit the proposal.
3. Check the proposal you submitted.

### Screenshots

Before submission:
<img width="946" alt="截圖 2023-09-26 上午8 15 16" src="https://github.com/chestercheng/pretalx/assets/21517083/87f1dfc8-f122-4dc0-add5-d76285270172">

After submission
<img width="923" alt="截圖 2023-09-26 上午8 15 24" src="https://github.com/chestercheng/pretalx/assets/21517083/339e43f4-e787-4150-a810-2329b36c11d5">

### Browser (software, desktop or mobile?) and version

Safari

### Operating system, dependency versions

MacOS 12.6

**Comment by sucitw** [comment]
@j8xixo12 Actually, the reason is because I changed the limitation. I found 300 characters may be not good enough for abstract. Sorry about that.

**Comment by chestercheng** [comment]
@sucitw thanks for your comment. However, there isn’t an issue here, so we can close it
