### ISSUE TITLE
Can not upload attach file

### ISSUE THREAD

**Issue by j8xixo12** [chestercheng/pretalx#2]
### Problem and impact

Upload some file
<img width="1103" alt="截圖 2023-12-10 上午11 32 32" src="https://github.com/chestercheng/pretalx/assets/21517083/07bcf2ff-baa0-45cf-9b43-8caaa5b4a4bf">

### Expected behaviour

File should be updated properly.

### Steps to reproduce

1.
2.
3.
4.

### Screenshots
<img width="1440" alt="截圖 2023-12-10 上午11 20 34" src="https://github.com/chestercheng/pretalx/assets/21517083/fa1ef1aa-d297-4b49-ad02-556996cc9f8a">

**Comment by chestercheng** [comment]
By default, NGINX limits file uploads to 1MB.
I’ve adjusted the setting, and the issue has been resolved.
